- generator.py
Should be "isdir" and not "isfolder".
> Fix generator func name

- generator.py
Needed for https://github.com/gtk-rs/gir/pull/985.
> Add option to not run `cargo fmt`

- examples/src/bin/entry_completion.rs
Moved from https://github.com/gtk-rs/examples/pull/321
> Fix entry_completion quit shortcut

- .github/workflows/CI.yml
WIP & depends on https://github.com/gtk-rs/checker/pull/13 being in first
> CI: fix gtk-rs checker

- glib/src/object.rs
Fixes https://github.com/gtk-rs/gtk-rs/issues/29
----
CC @haecker-felix
> glib: Add ObjectExt::connect_notify_local()

- glib/src/bridged_logging.rs
- glib/src/clone.rs
- glib/src/log.rs
- glib/tests/log.rs
Hope this has fixed issue #28.
> Allow log_domain to be null.

- cairo/src/enums.rs
- cairo/src/error.rs
- gio/src/inet_address.rs
- gio/src/subclass/application.rs
- glib/src/object.rs
- glib/src/variant_type.rs
- gtk/src/enums.rs
This is more flexible and still provides the old API in addition.
> Replace all Into impls with the corresponding From impls

- examples/src/bin/basic_subclass.rs
- examples/src/bin/listbox_model.rs
- gio/src/read_input_stream.rs
- gio/src/subclass/application.rs
- gio/src/subclass/input_stream.rs
- gio/src/subclass/io_stream.rs
- gio/src/subclass/output_stream.rs
- gio/src/subclass/seekable.rs
- gio/src/write_output_stream.rs
- glib/src/object.rs
- glib/src/subclass/mod.rs
- glib/src/subclass/object.rs
- glib/src/subclass/simple.rs
- glib/src/subclass/types.rs
- glib/src/wrapper.rs
- gtk/src/subclass/application.rs
- gtk/src/subclass/cell_renderer.rs
- gtk/src/subclass/cell_renderer_accel.rs
- gtk/src/subclass/cell_renderer_text.rs
- gtk/src/subclass/cell_renderer_toggle.rs
- gtk/src/subclass/container.rs
- gtk/src/subclass/dialog.rs
- gtk/src/subclass/icon_view.rs
- gtk/src/subclass/list_box.rs
- gtk/src/subclass/list_box_row.rs
- gtk/src/subclass/plug.rs
- gtk/src/subclass/socket.rs
- gtk/src/subclass/widget.rs
- gtk/src/subclass/window.rs
Glib tests seem to be passing, but Gtk and such needs to be updated.
> Make virtual methods take wrapper of type, not parent

- .github/workflows/docs.yml
- gdkx11/Gir.toml
- glib-macros/src/clone.rs
- glib/tests/clone.rs
Otherwise we get examples there as well, see https://gtk-rs.org/gtk-rs/gtk
> CI: don't use --workspace for docs

- generator.py
There is no point in keeping this check considering that we don't support python 2.
cc @MarijnS95 @sdroege
> Removing python2 code

- generator.py
Hopefully the final change to the generator for a while: autoformat to normalize newline usage and indentation, as well as normalize mixed quotations.
> generator: Autoformat and normalize quotation with `black`

- .github/workflows/CI.yml
- glib-macros/src/clone.rs
- glib/clone_tests/clone_compilation_errors.py
Fixes #183.
It also puts back the clone macro check on CI.
cc @haecker-felix
> Fix clone macro by allowing returned value with type parameters

- gtk/src/subclass/widget.rs
Details at #https://github.com/gtk-rs/gtk4-rs/pull/96 and https://github.com/gtk-rs/gtk4-rs/issues/95
> gtk: backport fix compute_expand vfunc

- pango/src/glyph.rs
> pango: implement FromGlibContainerAsVec for GlyphInfo

- cairo/build.rs
- cairo/sys/build.rs
- glib-macros/src/genum_derive.rs
- glib-macros/src/gflags_attribute.rs
- glib/src/translate.rs
> 2015 cleanup

- glib/src/date.rs
> Add checks in Date methods

- gio/Cargo.toml
- gio/src/gio_future.rs
- gio/src/input_stream.rs
- gio/tests/futures.rs
- glib/Cargo.toml
- glib/src/main_context_futures.rs
- glib/src/source_futures.rs
- glib/src/thread_pool.rs
Closes #251.
Sorry for the formatting change in `gio/Cargo.toml`, I can undo that if you want.
This touches some unsafe code, but I'm fairly certain it is no less sound than before 😅
> Reduce external dependencies for futures-related things

- examples/src/bin/composite_template.rs
- gtk/src/subclass/widget.rs
Copied from https://github.com/gtk-rs/gtk4-rs/pull/163.
> gtk: Implement Deref for TemplateChild

- gio/src/subclass/action_group.rs
- gio/src/subclass/action_map.rs
- gio/src/subclass/mod.rs
> add ActionMap/ActionGroup subclassing support

- gio/src/subclass/action_group.rs
> gio: use default methods when possible for ActionGroup

- examples/Cargo.toml
Backport of gtk-rs/gtk4-rs#161
> examples: Use autobins

- examples/Cargo.toml
- examples/build.rs
- examples/resources/resources.gresource.xml
- examples/src/bin/gtktest.glade
- examples/src/bin/gtktest.rs
- examples/src/bin/menu_bar.rs
- examples/src/bin/treeview.rs
- gio/src/lib.rs
- gio/src/resource.rs
Updates examples to use this.
Implementation of https://github.com/gtk-rs/gtk-rs/issues/259.
> gio: Add `glib-compile-resources` wrapper, and macro to include

- examples/src/bin/dialog.rs
- gtk/Cargo.toml
- gtk/src/dialog.rs
Backport of gtk-rs/gtk4-rs#149
> Add Dialog::run_future()

- glib/src/types.rs
> Implement StaticType on ()

- cairo/src/context.rs
This starts to address some of the less ambiguous parts of https://github.com/gtk-rs/gtk-rs/issues/74
> Cairo: make status() public

- glib/Gir.toml
- glib/src/auto/key_file.rs
See https://github.com/gtk-rs/gtk-rs/pull/284
> Mark 'key' parameter nullable for KeyFile's get_comment()

- glib-macros/src/clone.rs
- glib/tests/clone.rs
> Keep glib::clone spans

- glib/src/subclass/types.rs
- glib/src/types.rs
this also converts it to a HashMap instead of a Vec
> glib: rename TypeData::interface_data to class_data

- examples/src/bin/composite_template.rs
- gtk/src/prelude.rs
- gtk/src/subclass/widget.rs
- gtk/src/widget.rs
- gtk3-macros/src/attribute_parser.rs
- gtk3-macros/src/composite_template_derive.rs
- gtk3-macros/src/lib.rs
The source can be a file, a resource, or a string.
WIP: because I only quickly tested the file case using the example file
Also, it would be great to automagically hook into `class_init` instead of requiring to call `template_init`, but I have no idea on how to do that
> gtk: specify template as an attribute of CompositeTemplate

- glib/src/closure.rs
- glib/src/object.rs
See https://github.com/gtk-rs/gtk-rs/pull/302#discussion_r580474627
> glib: rename remaining _generic to _values

- .github/workflows/CI.yml
- .github/workflows/docs.yml
- .github/workflows/image.yml
Won't pass, requires making the new image public
cc @GuillaumeGomez
> CI: use the new docker image

- glib/src/source.rs
Closes #341. Please don't mind the copy-paste blueprints in the code ^^
CC @sdroege
> glib: Add _once variants to many methods

- glib-macros/src/clone.rs
- glib/clone_tests/clone_compilation_errors.py
- glib/tests/clone.rs
Fixes https://github.com/gtk-rs/gtk-rs/issues/356.
> Add support for async blocks in clone macro

- glib-macros/src/clone.rs
- glib/tests/clone.rs
> Fix async clone closures handling

- pango/Gir.toml
- pango/src/auto/layout_line.rs
- pango/src/layout.rs
- pango/src/lib.rs
Not sure if this is exactly right, let me know if I've missed anything.
- closes #374
> Add layout.rs, and manual LayoutLine::x_to_index impl

- glib/tests/clone.rs
- glib/tests/derive.rs
I also realized that we had a test that wasn't supposed to be here so I moved it to its own file.
> Add clone checks 3

- .github/workflows/docs.yml
build the docs with embed-lgpl-docs/dox features
> CI: fix docs job

- glib/src/value.rs
I still feel like I have no idea what I'm doing, but at least this compiles.
> glib: Implement StaticType, FromValue(Optional)? and SetValue(Optional)? for Value

- glib/src/gstring.rs
- glib/src/value.rs
> Improve Debug output for GString, SendValue

- gio/src/file.rs
Fixes https://github.com/gtk-rs/gtk-rs/issues/69
> gio: implement enumerate_children_async

- README.md
Fixes https://github.com/gtk-rs/gtk-rs/issues/15
> Add Ecosystem section to the README

- README.md
- atk/README.md
- cairo/README.md
- gdk-pixbuf/README.md
- gdk/README.md
- gdkx11/README.md
- gio/README.md
- glib/README.md
- graphene/README.md
- gtk/README.md
- pango/README.md
- pangocairo/README.md
Part of #244.
cc @bilelmoussaoui @sdroege
> Add minimum Rust supported version

- gio/src/subclass/input_stream.rs
- gio/src/subclass/io_stream.rs
- gio/src/subclass/output_stream.rs
- gio/src/subclass/seekable.rs
- glib/src/error.rs
- glib/src/value.rs
Fixes https://github.com/gtk-rs/gtk-rs/issues/55
> glib: add Error::into_raw()

- glib/src/object.rs
> glib: bind WeakRef::set()

- glib/src/gstring.rs
See https://github.com/gtk-rs/gtk4-rs/issues/286
> Improve/fix NULL handling in GString

- glib/src/translate.rs
Some low hanging fruits for https://github.com/gtk-rs/gtk-rs/issues/61. Lists are more of a pain :)
> glib: add some unit tests for translate

- atk/README.md
- cairo/Cargo.toml
- cairo/README.md
- gdk-pixbuf/README.md
- gdk/README.md
- gdkx11/Cargo.toml
- gdkx11/README.md
- gio/README.md
- glib/README.md
- graphene/README.md
- gtk/README.md
- pango/README.md
- pangocairo/README.md
Fixes #244.
Fixes #117.
I took example of what we had in gtk4-rs.
> Improve README files

- glib/src/lib.rs
- gtk/src/lib.rs
> Remove 'work in progress' statements

- glib-macros/src/gboxed_derive.rs
- glib-macros/src/gboxed_shared_derive.rs
- glib-macros/src/gflags_attribute.rs
- glib-macros/src/utils.rs
Also fallback to leaving it to user choice
> glib-macros: Try harder to find glib

- gtk/src/subclass/widget.rs
Copied from gtk4-rs, with `#[cfg]` added.
> gtk: Add `WidgetClassSubclassExt::{css_name,set_css_name}`

- gio/Gir.toml
- gio/src/auto/list_model.rs
> list_model: Rename object to item

- glib/src/char.rs
See https://github.com/gtk-rs/gtk-rs/issues/491
This leaves `fn new()` unchanged. Don't know if it would be better to change or remove that.
> glib: `From` and `TryFrom` implementations for working with `Char`

- gtk/Gir.toml
- gtk/src/auto/style_context.rs
- gtk/src/style_context.rs
> gtk: rename StyleContext::property to StyleContext::style_property

- cairo/src/context.rs
- cairo/src/device.rs
- cairo/src/font/font_face.rs
- cairo/src/font/font_options.rs
- cairo/src/font/scaled_font.rs
- cairo/src/image_surface.rs
- cairo/src/matrices.rs
- cairo/src/paths.rs
- cairo/src/patterns.rs
- cairo/src/pdf.rs
- cairo/src/ps.rs
- cairo/src/region.rs
- cairo/src/stream.rs
- cairo/src/surface.rs
- cairo/src/svg.rs
- cairo/src/user_data.rs
- cairo/src/xcb.rs
- examples/cairo_png/main.rs
- examples/cairo_test/main.rs
- examples/cairo_threads/drawing.rs
- examples/cairo_threads/main.rs
- examples/transparent_main_window/main.rs
This should handle most of the concerns @federicomenaquintero  had regarding the errors handling on Cairo's side
See #74 for details
> Make cairo error handling slightly better

- glib/src/subclass/mod.rs
This is an example that shows the problems with Option<Variant>.
Not sure if we want to add it or if you want to keep the example simple.
> Add a variant prop to the example

- gio/src/lib.rs
- gio/src/prelude.rs
> Add missing gio reexports

- .github/workflows/docs.yml
tested here https://github.com/gtk-rs/gtk4-rs/runs/2600462595?check_suite_focus=true
> CI: build versioned stable docs

- gdk/src/atom.rs
- gdk/src/event.rs
- gtk/src/border.rs
- gtk/src/entry_buffer.rs
- gtk/src/page_range.rs
> Generate missing doc aliases for newtypes

- .github/workflows/docs.yml
the gir-rustdoc script handles that for us already
> CI docs: drop manual rustdocflags

- atk/src/lib.rs
- gdk/src/lib.rs
- gtk/src/lib.rs
Also adds minimum required version of the library to every crate doc.
> Add minimal crate info

- Dockerfile
it will be used by the docs job for grabbing gtk-rs's logo/favicon
> image: pre-install wget

- .github/workflows/CI.yml
- .github/workflows/docs.yml
To be merged once #574 is merged
> CI: use the gtk3 image

- .github/workflows/docs.yml
so that it shows up in gtk-rs.org/gtk3-rs
> docs: add 0.9 release info

- .github/workflows/CI.yml
- README.md
- atk/README.md
- gdk/README.md
- gdkx11/README.md
- gtk/README.md
> Bump min required version to 1.53.0

- gtk/Gir.toml
- gtk/src/auto/clipboard.rs
- gtk/src/clipboard.rs
Fixes https://github.com/gtk-rs/gtk3-rs/issues/620.
> Make Clipboard::request_image pixbuf an Option

- gtk/Gir.toml
- gtk/src/auto/tree_view_column.rs
- gtk/src/lib.rs
- gtk/src/tree_view_column.rs
Fixes #226.
Thanks a lot @bilelmoussaoui for the code! It was mostly a copy/paste at this point. :laughing:
> Add missing methods on TreeViewColumn

- gtk/src/subclass/application.rs
- gtk/src/subclass/application_window.rs
- gtk/src/subclass/bin.rs
- gtk/src/subclass/box_.rs
- gtk/src/subclass/button.rs
- gtk/src/subclass/cell_renderer.rs
- gtk/src/subclass/cell_renderer_accel.rs
- gtk/src/subclass/cell_renderer_combo.rs
- gtk/src/subclass/cell_renderer_pixbuf.rs
- gtk/src/subclass/cell_renderer_progress.rs
- gtk/src/subclass/cell_renderer_spin.rs
- gtk/src/subclass/cell_renderer_spinner.rs
- gtk/src/subclass/cell_renderer_text.rs
- gtk/src/subclass/cell_renderer_toggle.rs
- gtk/src/subclass/container.rs
- gtk/src/subclass/dialog.rs
- gtk/src/subclass/drawing_area.rs
- gtk/src/subclass/event_box.rs
- gtk/src/subclass/fixed.rs
- gtk/src/subclass/header_bar.rs
- gtk/src/subclass/icon_view.rs
- gtk/src/subclass/list_box.rs
- gtk/src/subclass/list_box_row.rs
- gtk/src/subclass/plug.rs
- gtk/src/subclass/socket.rs
- gtk/src/subclass/stack.rs
- gtk/src/subclass/tree_view.rs
- gtk/src/subclass/widget.rs
- gtk/src/subclass/window.rs
> gtk: panic if gtk wasn't init at class_init

- .github/workflows/CI.yml
- gdk/Cargo.toml
- gdk/src/lib.rs
- gdk/src/wayland/mod.rs
- gdk/src/wayland/wayland_window.rs
- gdk/sys/Cargo.toml
- gdk/sys/src/lib.rs
- gdk/sys/src/manual.rs
> gdk: bind WaylandWindow manually

- atk/Gir.toml
- atk/src/auto/document.rs
- atk/src/auto/object.rs
- gdk/Gir.toml
- gdk/src/auto/functions.rs
- gtk/Gir.toml
- gtk/src/auto/dialog.rs
- gtk/src/auto/functions.rs
- gtk/src/auto/list_store.rs
- gtk/src/auto/menu.rs
- gtk/src/auto/recent_filter.rs
- gtk/src/auto/style_context.rs
- gtk/src/auto/text_buffer.rs
- gtk/src/auto/tree_store.rs
- gtk/src/functions.rs
- gtk/src/lib.rs
Based on https://github.com/gtk-rs/gtk3-rs/pull/548.
> Fix some gir annotations

- examples/list_box_model/row_data/imp.rs
- gtk/src/lib.rs
See https://github.com/gtk-rs/gtk-rs-core/pull/384
> Update for glib constructor renames

- gtk3-macros/src/lib.rs
> Simplify imports in doc example

- gtk/src/subclass/application.rs
- gtk/src/subclass/button.rs
- gtk/src/subclass/cell_renderer.rs
- gtk/src/subclass/cell_renderer_accel.rs
- gtk/src/subclass/cell_renderer_text.rs
- gtk/src/subclass/cell_renderer_toggle.rs
- gtk/src/subclass/container.rs
- gtk/src/subclass/dialog.rs
- gtk/src/subclass/icon_view.rs
- gtk/src/subclass/list_box.rs
- gtk/src/subclass/list_box_row.rs
- gtk/src/subclass/plug.rs
- gtk/src/subclass/scrolled_window.rs
- gtk/src/subclass/socket.rs
- gtk/src/subclass/widget.rs
- gtk/src/subclass/window.rs
See https://github.com/gtk-rs/gtk-rs-core/pull/437
> Rename `impl_` to `imp`

- gtk3-macros/src/lib.rs
Corresponds to https://github.com/gtk-rs/gtk4-rs/pull/942
> gtk3-macros: Add doc links to glib/gtk items

- .github/workflows/CI.yml
- README.md
- atk/Cargo.toml
- atk/README.md
- atk/sys/Cargo.toml
- gdk/Cargo.toml
- gdk/README.md
- gdk/sys/Cargo.toml
- gdkwayland/Cargo.toml
- gdkwayland/README.md
- gdkwayland/sys/Cargo.toml
- gdkx11/Cargo.toml
- gdkx11/README.md
- gdkx11/sys/Cargo.toml
- gtk/Cargo.toml
- gtk/README.md
- gtk/sys/Cargo.toml
- gtk3-macros/Cargo.toml
Corresponds to https://github.com/gtk-rs/gtk-rs-core/pull/434
> Update minimum supported Rust version to 1.57

- .github/workflows/windows.yml
As nicely suggested by @sdroege, I applied the patch from https://github.com/gtk-rs/gtk3-rs/pull/742.
> Fix windows CI

- Dockerfile
Part of https://github.com/gtk-rs/gtk-rs-core/issues/484
Depends on an image published from https://github.com/gtk-rs/gtk-rs-core/pull/676
> Base Dockerfile on gtk-rs-core image

- examples/basic_subclass/simple_application/imp.rs
- examples/basic_subclass/simple_window/imp.rs
- examples/composite_template/example_application_window/imp.rs
- gtk/src/subclass/application.rs
- gtk/src/subclass/button.rs
- gtk/src/subclass/cell_renderer.rs
- gtk/src/subclass/cell_renderer_accel.rs
- gtk/src/subclass/cell_renderer_text.rs
- gtk/src/subclass/cell_renderer_toggle.rs
- gtk/src/subclass/container.rs
- gtk/src/subclass/dialog.rs
- gtk/src/subclass/entry.rs
- gtk/src/subclass/icon_view.rs
- gtk/src/subclass/list_box.rs
- gtk/src/subclass/list_box_row.rs
- gtk/src/subclass/plug.rs
- gtk/src/subclass/scrolled_window.rs
- gtk/src/subclass/socket.rs
- gtk/src/subclass/widget.rs
- gtk/src/subclass/window.rs
It's doing the same thing and is shorter.
> Move from `imp.instance()` to `imp.obj()`

- gtk/src/response_type.rs
This looks like the only one here that needs a manual implementation
> gtk: implement From<ResponseType> for Value

- examples/build.rs
Ref https://github.com/gtk-rs/gtk-rs-core/pull/917
> examples: Adapt to glib-build-tools breaking change

- gtk/src/subclass/menu_button.rs
- gtk/src/subclass/mod.rs
- gtk/src/subclass/toggle_button.rs
A couple of patches to allow subclassing Toggle and Menu buttons.
> Allow subclassing ToggleButton and MenuButton

- .github/workflows/docs.yml
- gdkwayland/src/wayland_window.rs
- gdkwayland/sys/src/lib.rs
- gtk/src/file_chooser.rs
- gtk/src/gesture_stylus.rs
- gtk/src/lib.rs
- gtk/src/prelude.rs
- gtk/src/subclass/mod.rs
> Backport #838

- examples/cairo_test/main.rs
- examples/cairo_threads/main.rs
- examples/clipboard_simple/main.rs
- examples/gtk_builder_basics/main.rs
- examples/gtk_builder_signal/main.rs
- examples/gtk_test/main.rs
- examples/multi_window/main.rs
- examples/progress_tracker/main.rs
- examples/transparent_main_window/main.rs
- gtk/src/subclass/socket.rs
- gtk/src/subclass/widget.rs
In the shuffle from Inhibit(bool), to ControlFlow, to Propagtaion we ended up flipping some value. In particular in the widget subclass code and in the example.
> Properly use the Propagation values
