gtk-rs/gtk3-rs

- glib/Gir.toml
- glib/src/auto/functions.rs
- glib/src/functions.rs
This tweaks `get_charset()` signature and logic to properly return
both the charset label and the UTF-8 boolean.
> glib/functions: fix get_charset logic

- glib-macros/src/genum_derive.rs
- glib-macros/src/gflags_attribute.rs
Otherwise code using it derive macros needs to have it in scope already,
which is not very user-friendly.
----
CC @gdesmott
> glib-macros: Use absolute paths to the StaticType trait

- .github/workflows/CI.yml
- Cargo.toml
- gio/sys/tests/abi.rs
> CI: add a simple github action

- generator.py
It'll be followed by this patch on `gir`:
```
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -157,23 +157,17 @@ jobs:
cd tests/sys/secret-sys
cargo test -- --nocapture
if: matrix.os == 'windows-latest'
-      - name: "Acquire GTK"
+      - name: "Acquire gtk-rs"
uses: actions/checkout@v2
with:
-          repository: gtk-rs/gtk
+          repository: gtk-rs/gtk-rs
ref: master
-          path: gtk-test
+          path: gtk-rs
if: matrix.os == 'ubuntu-latest'
- name: "Attempt to rebuild GTK gir"
-        run: cd gtk-test && ../target/release/gir -d ../tests/gir-files/ -o . && rm ../Cargo.* && cargo build
+        run: cd gtk-rs && python3 generator.py --gir-path ../target/release/gir --gir-files ../tests/gir-files/ && rm ../Cargo.* && cargo build
if: matrix.os == …
```
> Improve generator.py script to make CI job easier

- generator.py
It's all because gobject has a GIR file named `Gir_gobject.toml`, which didn't match what `generator.py` was expecting. :)
> Also regen gobject if needed

- .github/workflows/docs.yml
Build nightly docs & publish them through github pages. The job only runs when something is merged in master. The same thing could be used in the future to build & publish stable docs if needed.
> CI: add a docs job

- glib/src/object.rs
glib_wrapper! automatically does this and having it included here makes
usage of the IsA trait simpler.
> glib: Require all the Value traits to be implemented for ObjectType

- .github/workflows/CI.yml
Ensures that the files were properly re-generated
Depends on https://github.com/gtk-rs/gir/issues/979
> CI: add a regen check job

- .github/workflows/CI.yml
- generator.py
`def_check_submodule` was always passing `'gir'` even when called with `gir-files`, and the `depth` used to derive whether `Gir.toml` resides in a `sys` crate is inaccurate when specifying eg. `**/sys` on the command line (as that'd be level 0).
In addition, convert path handling to `pathlib` whose paths are constructed and checked during argument parsing.
Please double-check if I overlooked a path anywhere that's still a string instead of `Path`.
EDIT: With pathlib we might also replace the depth-first search in `regen_crates` with `path.glob` or `path.rglob` on `**/Gir*.toml`?
> generator: Convert to pathlib, fix wrong path passed to various executables

- gtk/src/subclass/button.rs
- gtk/src/subclass/mod.rs
Was added to gtk4-rs in https://github.com/gtk-rs/gtk4-rs/pull/57
This doesn't include the deprecated virtual methods in gtk3 that are not in gtk4. Those could be added, but new projects probably shouldn't be using them anyway.
> Subclassing for GtkButton, backported from gtk4-rs

- glib/src/gstring.rs
Needed by https://github.com/gtk-rs/gtk4-rs/pull/89
> glib: implement FromGlibContainer for GString

- Cargo.toml
- examples/Cargo.toml
- examples/src/bin/composite_template.rs
- examples/src/bin/composite_template.ui
- gtk/Cargo.toml
- gtk/src/lib.rs
- gtk/src/subclass/mod.rs
- gtk/src/subclass/widget.rs
- gtk3-macros/Cargo.toml
- gtk3-macros/src/composite_template_derive.rs
- gtk3-macros/src/lib.rs
- gtk3-macros/src/util.rs
Backports support for composite templates from gtk4-rs.
We can't use gtk-macros as the name of the proc macro crate due to a conflict with an existing gtk-macros crate.
> Backport composite templates from gtk4-rs

- gio/sys/src/manual.rs
It was broken to build gio package on windows platform.
16 |         self::winapi::shared::ws2def::AF_UNSPEC;
|               ^^^^^^ could not find `winapi` in `self`
I checked it on windows 10.
> gio/sys: resolve winapi reference

- pango/src/lib.rs
Otherwise gir produces code that uses `pango::Glyph*` which can't be found
```
error[E0412]: cannot find type `GlyphInfo` in crate `pango`
--> gsk4/src/auto/text_node.rs:49:44
|
49 |       pub fn get_glyphs(&self) -> Vec<pango::GlyphInfo> {
|                                              ^^^^^^^^^
| 
::: /home/bilelmoussaoui/.cargo/git/checkouts/gtk-rs-48ef14c1f17c79fb/0ef3630/pango/src/auto/glyph_item.rs:8:1
|
8  | / glib::glib_wrapper! {
9  | |     #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
10 | |     pub struct GlyphItem(Boxed<ffi::PangoGlyphItem>);
11 | |
...  |
16 | |     }
17 | | }
| |_- similarly named struct `GlyphItem` defined here
|
help: a struct with a similar name exists
|
49 |     pub fn get_glyphs(&self) -> Vec<pango::GlyphItem> {
| …
```
> pango: export Glyph* manual types

- glib/src/signal.rs
I don't know if it makes sense to put this docstring here, but since non clone structs can be a little unwieldy I think an example could help some lost soul in the future.
> glib/signal.rs: Add docstring for SignalHandlerId

- gio/Gir.toml
- gio/src/auto/settings.rs
- gio/src/settings.rs
Using boxed `Fn` mainly to have a reasonable way to pass `None`.
> gio: Add `Settings::bind_with_mapping()` binding

- glib-macros/src/downgrade_derive/enums.rs
- glib-macros/src/downgrade_derive/fields.rs
- glib-macros/src/downgrade_derive/mod.rs
- glib-macros/src/downgrade_derive/structs.rs
- glib-macros/src/lib.rs
- glib/src/clone.rs
- glib/src/lib.rs
- glib/tests/clone.rs
I do not know if this is a good idea or not to use `gtk` crate in doc-tests of `glib-macros` crate. So, all examples are totally artificial and marked as `ignored`.
> Implement derive macro for Downgrade/Upgrade traits

- glib/src/subclass/mod.rs
- glib/src/subclass/types.rs
Add a new wrapper type, `InitializingObject`, to store the object pointer during `instance_init()`. Binding crates are expected to define traits and implement them for `InitializingObject` to expose safe methods. Notably, this is required for `gtk_widget_init_template()`.
> subclass: Hook up instance_init()

- gio/src/subclass/mod.rs
- gtk/src/subclass/mod.rs
@bilelmoussaoui Same change is also needed for gtk4 I guess
> Consistently re-export subclassing preludes of dependency crates

- examples/src/bin/basic_subclass.rs
- examples/src/bin/composite_template.rs
- examples/src/bin/gio_task.rs
- examples/src/bin/listbox_model.rs
- gio/src/read_input_stream.rs
- gio/src/subclass/application.rs
- gio/src/subclass/input_stream.rs
- gio/src/subclass/output_stream.rs
- gio/src/task.rs
- gio/src/write_output_stream.rs
- glib/Gir_GObject.toml
- glib/src/gobject/auto/flags.rs
- glib/src/gobject/auto/mod.rs
- glib/src/gobject/flags.rs
- glib/src/gobject/mod.rs
- glib/src/subclass/boxed.rs
- glib/src/subclass/interface.rs
- glib/src/subclass/mod.rs
- glib/src/subclass/object.rs
- glib/src/subclass/signal.rs
- glib/src/subclass/types.rs
Supersedes https://github.com/gtk-rs/gtk-rs/pull/31 for now, I'll update that one to only include the `Value` changes once this one is merged.
TODO
> Subclassing refactoring

- gio/Cargo.toml
`serial_test` since [0.3](https://github.com/palfrey/serial_test/releases/tag/v0.3.0) includes `serial_test_derive` and lets you use the macro without needing to directly include `serial_test_derive`
> Don't need serial_test_derive

- gio/src/task.rs
warning: unnecessary trailing semicolon
--> gtk-rs/gio/src/task.rs:30:10
|
30 |         };
|          ^ help: remove this semicolon
|
= note: `#[warn(redundant_semicolons)]` on by default
> gio: Remove unneeded trailing semicolon

- .github/workflows/windows.yml
- glib/src/translate.rs
Add a build-win job, which builds the create with MSVC.
The job builds the gtk dependencies using gvsbuild and caches them
so that they are not rebuilt on each run.
For now I just added the stable toolchain and x86_64 arch.
Many steps are currently failing (eg ABI checks), so I left them
commented out.
> CI: add CI for Windows

- glib/src/types.rs
- graphene/sys/Cargo.toml
Useful when Types need to be used in sets or as map keys. Hash is
already derived, just PartialOrd and Ord were missing.
> glib: Derive Ord on Type

- examples/src/bin/entry_completion.rs
- examples/src/bin/iconview_example.rs
- examples/src/bin/list_store.rs
- examples/src/bin/tree_model_sort.rs
- gio/src/subclass/list_model.rs
- gio/src/task.rs
- glib-macros/src/gboxed_derive.rs
- glib-macros/src/genum_derive.rs
- glib-macros/src/gflags_attribute.rs
- glib-macros/tests/test.rs
- glib/src/closure.rs
- glib/src/object.rs
- glib/src/param_spec.rs
- glib/src/subclass/boxed.rs
- glib/src/subclass/interface.rs
- glib/src/subclass/mod.rs
- glib/src/subclass/object.rs
- glib/src/subclass/types.rs
- glib/src/types.rs
- glib/src/value.rs
- glib/src/variant.rs
- gtk/src/subclass/container.rs
- Make `Type` leaner, replace enum with assoc consts.
- Pass `Type` by value, where possible
- Introduce `Type::is_valid` and use it
- Make `Type::name` return a `str`
> glib: Improve the API of Type

- glib/src/object.rs
This series contains a hopefully easy-to-follow series of refactorings, followed by a commit fixing an actual bug:
When the callback returned an `Object`-typed `Value` containing a `None`, the code accepted it and transmuted the `Value` into the `return_type`, even if that `Type` wasn't an `Object`, with undefined behavior.
If the `Value` doesn't contain `Some` `Object`, check the `Value`'s `Type` against the `return_type` instead.
>  connect_unsafe: Refactor, then don't ignore the return_type for null objects 

- examples/src/bin/basic_subclass.rs
- examples/src/bin/composite_template.rs
- examples/src/bin/gio_task.rs
- examples/src/bin/listbox_model.rs
- gio/src/read_input_stream.rs
- gio/src/subclass/application.rs
- gio/src/subclass/input_stream.rs
- gio/src/subclass/output_stream.rs
- gio/src/task.rs
- gio/src/write_output_stream.rs
- glib-macros/Cargo.toml
- glib-macros/src/lib.rs
- glib-macros/src/object_subclass_attribute.rs
- glib/src/lib.rs
- glib/src/subclass/mod.rs
- glib/src/subclass/object.rs
- glib/src/subclass/types.rs
- gtk3-macros/src/lib.rs
Proposed in https://github.com/gtk-rs/gtk-rs/issues/322.
This replaces `object_subclass!` while also magically adding support for associated type defaults, and making `new()` call `Default::default()`.
A draft because I still need to update the other crates to use this, test it a bit more, and perhaps tweak the errors it produces and the documentation.
A proc macro like this here could be useful for other things. For instance, to address https://github.com/gtk-rs/gtk-rs/issues/215 by splitting `type_data` and `get_type` into a separate `unsafe trait`. That is not implemented here.
> glib: `#[object_subclass]` proc macro.

- .github/workflows/image.yml
- Dockerfile
This adds a `Dockerfile` and a CI job that builds the image and publish it on Github Packages containers registry. A future PR will migrate the CI to use it as we need to merge it first to get the image built & published.
> CI: add a docker image

- gio/src/subclass/io_stream.rs
- gio/src/subclass/list_model.rs
- glib/src/object.rs
A returned reference can become dangling by a concurrent `set_data` or
`steal_data`. Return a pointer instead.
> object: Return a pointer from get_qdata, not a reference

- glib/src/object.rs
Similar to connect/connect_local/connect_unsafe but takes a SignalId instead of a signal name
Fixes #320
> glib: add ObjectExt::connect_id & other variants

- gio/src/subclass/action_group.rs
- gio/src/subclass/action_map.rs
- gio/src/subclass/list_model.rs
- gio/src/subclass/seekable.rs
- glib/src/lib.rs
- glib/src/object.rs
- glib/src/subclass/object.rs
- glib/src/subclass/types.rs
Without this it was possible to cast from a Class<T> to a Class<U> where
U is an interface type. This doesn't work as interface structs are to be
retrieved differently than just casting and would cause memory unsafety
issues.
Fixes https://github.com/gtk-rs/gtk-rs/issues/348
> glib: Distinguish between classes and interfaces at the type level

- examples/src/bin/listbox_model.rs
See https://github.com/gtk-rs/gtk-rs/issues/354
> glib: Fix compilation of listbox_model example

- gtk/Gir.toml
- gtk/src/auto/widget.rs
As described in #358, unlike most `bool`-returning signals on `Widget`, the `drag-motion` and `drag-drop` signals' return values are *not* interpreted as inhibiting further signal propagation. However, the person who wrote their Gir assumed that they were. (Understandably, as the official documentation for these signals is pretty sparse.) This PR modifies them to return `bool` instead of `Inhibit`.
- `drag-motion`: `true` → a drop here will succeed, `false` → a drop here will fail; not `Inhibit`-like, modified
- `drag-drop`: `true` → a drop here succeeded, `false` → a drop here failed; not `Inhibit`-like, modified
- `drag-failed`: `true` → carry out the standard "drag failed" animation, `false` → don't carry out that animation; I left this as `Inhibit` since it seems to fit
I wasn't able …
> Make `drag-motion` and `drag-drop` signals return `bool` instead of `Inhibit`

- glib-macros/src/lib.rs
> glib-macros: Fix typo: doman -> domain

- glib/src/subclass/mod.rs
This bit me in https://gitlab.gnome.org/GNOME/librsvg/-/merge_requests/490#note_1064620 - the example in the subclass docs seems wrong.
> Fix use of gflags attribute in the subclass example

- glib/src/source.rs
Here I was, wondering why my callbacks weren't firing
> glib: Actually call the function in _once wrappers

- pango/src/layout.rs
While I was working on #375 I thought it would make sense to fix another problem I've run into, which is that the various fields on the `PangoLayoutLine` struct are not exposed in a friendly way.
This is a draft; it currently includes the commit from #375, and I'll clean it up if & when that patch is merged.
Two questions:
- Is this desirable, and is my approach okay?
- Is there some way I can expose the `resolved_dir` field? In the auto-generated `PangoLayoutLine` struct this field is missing, and there's a comment `// field resolved_dir has incomplete type`. Is this something that I can fix?
> Expose layout line fields

- gio/src/unix_input_stream.rs
- gio/src/unix_output_stream.rs
- gio/src/win32_input_stream.rs
- gio/src/win32_output_stream.rs
Add two variants, take_fd/handle and with_fd/handle which respectively
take ownership or not of the fd/handle. This models the "close"
boolean of the C api.
Fixes https://github.com/gtk-rs/gtk-rs/issues/381
> Replace _new constructor for Unix/Win32 Input and Output streams

- generator.py
This change cleans up handling of the default gir directory, and makes sure the `-d` flag is prepended to every path. Before the command would contain a single `-d` flag followed by a `list` of paths, which cannot be passed to an executable verbatim:
The following error occurred: expected str, bytes or os.PathLike object, not list
Do you want to continue? [y/N] ^CTraceback (most recent call last):
File "./generator.py", line 189, in <module>
Fixes: c33495c ("Don't set a default value for the -d option")
CC @GuillaumeGomez
> generator: Iterate gir directories passed on the command line

- pango/src/layout.rs
My understanding was that the hit positions were relative to the
start of the line, but testing shows that they are relative to
the start of the full text.
> pango: Fix x_to_index docs

- glib-macros/src/lib.rs
It referenced a "run_fail" attribute, which does not seem to exist.
> Fix clone macro docs

- glib/src/value_array.rs
Those are expected for an array type, since we have getters on
ValueArray itself (along with the [Value] deref).
> Add ValueArray::len()/is_empty()

- glib/src/param_spec.rs
- glib/src/subclass/signal.rs
- glib/src/utils.rs
Fixes #409
Panics if handed a non canonical name
> glib: Only allow canonical names in property and signal builders

- gio/Gir.toml
- gio/src/auto/dbus_connection.rs
- gio/src/auto/dbus_proxy.rs
https://developer.gnome.org/gio/stable/GDBusProxy.html says the proxy can be used from multiple threads, so I assume this is correct.
> gio: Mark `DBusProxy` as `send+sync` and regenerate

- .github/workflows/docs.yml
this would allow us to publish the stable docs in a separate subdir later on
> CI: install git docs in a subdir

- gtk/Gir.toml
- gtk/src/auto/label.rs
- gtk/src/auto/link_button.rs
Never take Option, since one can simply use new() if they do not
want to specify a string.
Fixes https://github.com/gtk-rs/gtk-rs/issues/133
> gtk: make all with_label and with_mnemonic constructors consistent

- glib/src/lib.rs
- glib/src/value.rs
It's not very useful in practice and there seems to be no usage of it.
If a "typed value" is needed then the proper Rust type can be used as
well and there's no reason to keep it in a GValue wrapper.
----
Extracted from https://github.com/gtk-rs/gtk-rs/pull/31 for easier reviewing and smaller PRs.
> glib: Remove glib::TypedValue

- glib/src/array.rs
- glib/src/lib.rs
This allows me to write manual bindings for a boxed property returning a GArray
> glib: add Array wrapper

- .github/workflows/CI.yml
- README.md
- atk/README.md
- cairo/README.md
- gdk-pixbuf/README.md
- gdk/README.md
- gdkx11/README.md
- gio/README.md
- glib-macros/src/gboxed_shared_derive.rs
- glib-macros/src/lib.rs
- glib-macros/tests/test.rs
- glib/README.md
- glib/src/lib.rs
- glib/src/subclass/boxed.rs
- glib/src/subclass/mod.rs
- glib/src/subclass/object.rs
- glib/src/subclass/shared.rs
- graphene/README.md
- gtk/README.md
- pango/README.md
- pangocairo/README.md
Added a SharedType trait that allows implementing reference-counted
types in terms os std::sync::Arc. In particular, the ffi methods that
increment reference counting can return always the same pointer value.
Also, added a `Shared` derive macro, similar to the existing `GBoxed`
one, that simplifies the creation of Shared objects.
> glib: glib-macros: add SharedType and Shared derive macro

- gdk/src/event.rs
- glib/src/param_spec.rs
Implementing it requires ensuring that downcast() works.
Fixes https://github.com/gtk-rs/gtk-rs/issues/430
> glib: mark ParamSpecType trait as unsafe

- glib/Gir.toml
This is a boxed record that cannot be generated due to missing memory management functions.  That was previously silently permitted (and logged somewhere along the rest of the warnings) but is now proactively disallowed thanks to https://github.com/gtk-rs/gir/pull/1103.  Remove this type from the `generate` list since it has no effect anyway.
> glib: Remove un-generatable type UriParamsIter

- gio/src/lib.rs
- gio/src/prelude.rs
- gio/src/tls_connection.rs
Noticed in [1] that this trait has ManualExt written the wrong way around, and is exported from the crate root instead of the prelude where all other traits are reexported.
[1]: https://github.com/gtk-rs/gir/pull/1111#issuecomment-826319140
CC @bilelmoussaoui
> gio: Rename TlsConnectionManualExt to ExtManual and export from prelude

- .github/workflows/CI.yml
- .github/workflows/docs.yml
This is a bit more elegant than manually invoking `rustup component add`.  Afaik it is synonymous to `rustup toolchain install <toolchain> --components <components>` which is why it has not been applied to the clippy step in CI.yml, as that would limit available nightlies when clippy is only used in the `stable` matrix runs.
> GH workflows: Use actions-rs/toolchain `components` to install clippy

- glib/Gir.toml
- glib/src/functions.rs
The API is not great, and I kept the plain `i32` flags argument since also the glib function takes the raw libc flag.
On the other hand this function is useful to bind because I did not find an equivalent function in `std` and I need the fd to pass to `SubprocessLauncher::take_fd`
> glib: manually bind g_unix_open_pipe

- .github/workflows/docs.yml
With this the job will start automatically when a release is published and the docs will hopefully be deployed to the stable subdirectory instead of the git one.
> CI: publish release docs in a separate subdir

- glib-macros/src/gboxed_derive.rs
- glib-macros/src/gboxed_shared_derive.rs
- glib-macros/src/genum_derive.rs
- glib-macros/src/gflags_attribute.rs
- glib-macros/tests/test.rs
- glib/src/subclass/boxed.rs
- glib/src/subclass/mod.rs
- glib/src/subclass/shared.rs
The proper way is to call ::static_type()
> glib-macros: do not export ::type_() for boxed types

- gio/src/unix_mount_entry.rs
- glib/src/utils.rs
relevant c code
```c
if (!e.user_name)
e.user_name = g_strdup ("somebody");
if (!e.real_name)
e.real_name = g_strdup ("Unknown");
```
```c
/* If we have been denied access to /etc/passwd (for example, by an
* overly-zealous LSM), make up a junk value. The return value at this
* point is explicitly documented as ‘undefined’. */
if (home_dir == NULL)
{
g_warning ("Could not find home directory: $HOME is not set, and "
"user database could not be read.");
home_dir = g_strdup ("/");
}
```
and the rest according to docs and `auto/unix_mount_entry.rs`
> glib: fix some nullables

- examples/README.md
I was looking for these examples and it too me a while in the whole renaming. This should save some time for the next person.
> Fix links to GIO examples

- gtk/src/rt.rs
there's no need to ensure we are initializing gtk on the main thread
if gtk was not initialized yet
> gtk: drop MainContext check

- .github/workflows/docs.yml
because it's an ubuntu based image instead of a fedora one
> CI: use apt instead of dnf

- .github/workflows/docs.yml
Otherwise the  condition fails and the value is always set to `git`  which is the reason why we still don't have stable docs for the released versions. Once this patch is merged, a temporary `0.14` release has to be created to trigger the docs job
> docs: fix the release condition

- .github/workflows/docs.yml
otherwise gir-rustdoc says our latest docs are old :p
> CI: latest docs should be the first

- gtk/src/rt.rs
Fixes partially gtk-rs/gtk-rs-core#186, because gtk4 still has that issue.
> Acquire and leak main context in gtk::init()

- gtk/src/subclass/button.rs
As far as I understand, this was incorrect.
This seems to be all that's required to compile with the `IsSubclassable` change in https://github.com/gtk-rs/gtk-rs-core/pull/241.
> gtk: Make `ButtonImpl` depend on `BinImpl`

- gtk/Gir.toml
- gtk/src/auto/window.rs
Fixes #604.
`focus_widget` seemed wrong too so I picked `focused_widget` instead.
> Rename Window::focus into Windows::focused_widget

- gdk/src/atom.rs
> remove unsafe marker for gdk::Atom::value

- gtk/src/rt.rs
It returns 1 in the case we care about (main thread) and 0 or -1
otherwise.
> gtk: Fix usage of pthread_main_np() return value

- gtk/Gir.toml
- gtk/src/auto/print_operation.rs
- gtk/src/lib.rs
- gtk/src/print_operation.rs
This moves `gtk_print_operation_get_error` to a manual wrapper.
It quacks like a fallible function, but it isn't. That was resulting in a wrong
auto-generated wrapper.
> gtk: manually implement gtk_print_operation_get_error

- gtk/Gir.toml
- gtk/src/auto/builder.rs
- gtk/src/builder.rs
This adds a manual implementation for all the GtkBuilder methods
that are using unconventional (non gboolean) return codes.
Closes: https://github.com/gtk-rs/gtk3-rs/issues/690
> gtk/builder: manually implement several methods (custom return codes)

- gtk/Gir.toml
- gtk/src/container.rs
- gtk/src/lib.rs
- gtk/src/prelude.rs
- gtk/sys/src/manual.rs
It requires a manual implementation to check if the property exists
and is readable/writeable and also of the correct type.
Fixes #664
> manually implement Container::(get|set)_property

- gdkwayland/README.md
The folder name is `gdkwayland` so the `Cargo.toml` snippets should have `gdk-wayland = { git = "https://github.com/gtk-rs/gtk3-rs.git", package = "gdkwayland" }` instead of `gdk-wayland = { git = "https://github.com/gtk-rs/gtk3-rs.git", package = "gdk-wayland" }`.
Maybe a comment noting that the package hasn't been released yet and can only be used by the git style should be added too?
> Fix `gdkwayland` pkg name in README.md snippets

- atk/Cargo.toml
- atk/sys/Cargo.toml
- examples/Cargo.toml
- gdk/Cargo.toml
- gdk/sys/Cargo.toml
- gdkwayland/Cargo.toml
- gdkwayland/sys/Cargo.toml
- gdkx11/Cargo.toml
- gdkx11/sys/Cargo.toml
- gtk/Cargo.toml
- gtk/sys/Cargo.toml
This makes sure we're building against the latest 0.15 versions while
still being able to publish to crates.io.
> Point to git 0.15 versions of the gtk-rs-core dependencies

- gtk/Gir.toml
- gtk/src/auto/text_iter.rs
- gtk/src/auto/tree_iter.rs
So that a `struct` using these types can also auto derive `Debug`.
Another solution could be to add a `Debug` `impl` in manual code,
but since these are iterators, there's not much we can show.
Other `boxed_inline` candidates in `gtk-rs-core` and `gtk3-rs` use manual `Debug` `impl` AFAICT.
> gtk/{Text,Tree}Iter: derive Debug

- gtk/src/cell_renderer_pixbuf.rs
Fixes https://github.com/gtk-rs/gtk3-rs/issues/717
----
Only the first commit should be backported.
> gtk: Use `u32` as underlying type for the `stock-size` property of `CellRendererPixbuf`

- gdk/src/geometry.rs
Fixes https://github.com/gtk-rs/gtk3-rs/issues/718
> gdk: Add constructor for `gdk::Geometry`

- gdk/src/visual.rs
- gtk/src/signal.rs
- gtk/src/text_buffer.rs
- gtk/src/tree_path.rs
Passing `NULL` to `slice::from_raw_parts` is invalid.
> Handle empty slices correctly

- gdk/Cargo.toml
- gdk/src/rt.rs
- gtk/Cargo.toml
- gtk/src/rt.rs
This is useful for building a `cdylib`/`staticlib` with C ABI bindings, where `gtk_init()` will be called from outside Rust.
> gtk: Add an `unsafe-assume-initialized` feature

- .github/workflows/CI.yml
- .github/workflows/docs.yml
- .gitmodules
- README.md
- atk/Cargo.toml
- atk/README.md
- atk/sys/Cargo.toml
- gdk/Cargo.toml
- gdk/README.md
- gdk/sys/Cargo.toml
- gdkwayland/Cargo.toml
- gdkwayland/README.md
- gdkwayland/sys/Cargo.toml
- gdkx11/Cargo.toml
- gdkx11/README.md
- gdkx11/sys/Cargo.toml
- gtk/Cargo.toml
- gtk/README.md
- gtk/sys/Cargo.toml
- gtk3-macros/Cargo.toml
This makes sure that cargo does not clone and checkout all the
submodules if pointing to this repository as a git dependency.
To checkout the submodules `git submodule update --checkout` can be
used.
> Don't checkout submodules by default

- atk/Cargo.toml
- gdkwayland/Cargo.toml
- gdkx11/Cargo.toml
- gtk/Cargo.toml
Analogous to: https://github.com/gtk-rs/gtk-rs-core/pull/778
Whenever a crate is published on crates.io, its documentation is automatically built on docs.rs regardless of the documentation field in the Cargo.toml file. On docs.rs it is possible to look at all previous versions. This is why there is value in having working builds on docs.rs. Having broken builds on docs.rs also prevents crates using that library from providing their own documentation on docs.rs. I enabled the dox feature wherever it is available to ensure the docs always build, even if the dependencies are not available.
> Activate dox feature wherever possible

- gdk/Gir.toml
- gdk/src/auto/functions.rs
To my understanding `gdk::set_allowed_backends()` should be called (when needed) before the `init()`  
https://docs.gtk.org/gdk3/func.set_allowed_backends.html
> This call must happen prior to gdk_display_open(), gtk_init(), gtk_init_with_args() or gtk_init_check() in order to take effect.
The way I added the assertion skip might not be the way intended.
Please let me know.
> Skip init assertion for gdk::set_allowed_backends

- examples/menu_bar_system/main.rs
glib-rs mainline takes the variant as a ref
> Fix menu bar example

- gdk/src/atom.rs
- gtk/Gir.toml
See https://github.com/gtk-rs/gir/pull/1447
> Prepare for gir collections

- gtk3-macros/Cargo.toml
The code in this crate uses features of "syn" which are only present
when the default features are enabled. This previously worked "by
accident" because other crates in the dependency tree pulled in the
"default" feature of syn, but these crates have started moving to
syn v2, so this is no longer the case.
> gtk3-macros: enable default features of syn

- gtk3-macros/Cargo.toml
- gtk3-macros/src/attribute_parser.rs
There's also a `NestedMeta` API in syn 2.0, but it's callback based for some reason and I'm much more familiar with the custom parsing API. The error messages should be of similar quality to before, on average.
> Upgrade syn to 2.0

- .github/workflows/docs.yml
- gdkwayland/src/wayland_window.rs
- gdkwayland/sys/src/lib.rs
- gtk/src/file_chooser.rs
- gtk/src/gesture_stylus.rs
- gtk/src/lib.rs
- gtk/src/prelude.rs
- gtk/src/subclass/mod.rs
This PR is analogous to https://github.com/gtk-rs/gtk-rs-core/pull/1078.
Without it, the builds will likely break on docs.rs, which would leave may crates relying on gtk3-rs related crates without working docs.
> More fixes for docsrs attribute

- examples/cairo_test/main.rs
- examples/cairo_threads/main.rs
- examples/clipboard_simple/main.rs
- examples/gtk_builder_basics/main.rs
- examples/gtk_builder_signal/main.rs
- examples/gtk_test/main.rs
- examples/multi_window/main.rs
- examples/progress_tracker/main.rs
- examples/transparent_main_window/main.rs
- gtk/src/subclass/socket.rs
- gtk/src/subclass/widget.rs
In the shuffle from Inhibit(bool), to ControlFlow, to Propagtaion we ended up flipping some value. In particular in the widget subclass code and in the example.
> Properly use the Propagation values
